name: flutter_sweet_shop_app_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^3.0.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.10.0
  google_fonts: ^6.2.1
  animate_do: ^4.2.0
  flutter_svg: ^2.2.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  readmore: ^3.0.0
  dotted_border: ^3.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/